version: 1.0.0.{build}
image:
- Visual Studio 2017
- Ubuntu1804

build_script:
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTING=ON ..
  - cmake --build . --config Release

test_script:
  - ctest

for:
-
  matrix:
    only:
      - image: Ubuntu1804

  after_test:
  - cpack -G TBZ2
  - cpack -G TXZ
  - cpack -G DEB
-
  matrix:
    only:
      - image: Visual Studio 2017

  after_test:
  - cpack -G ZIP
  - cpack -G 7Z
  - cpack -G NSIS


artifacts:
  - path: 'build/libriffcpp-*.zip'
  - path: 'build/libriffcpp-*.7z'
  - path: 'build/libriffcpp-*.tar.bz2'
  - path: 'build/libriffcpp-*.tar.xz'
  - path: 'build/libriffcpp-*.deb'
  - path: 'build/libriffcpp-*.exe'