version: 1.0.0.{build}
image:
- Visual Studio 2017
- Ubuntu1804

platform:
  - x86
  - x64

for:
-
  matrix:
    only:
      - image: Ubuntu1804
      - platform: x64

  build_script:
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTING=ON ..
    - cmake --build . --config Release

  test_script:
    - ctest

  after_test:
  - cpack -G TBZ2
  - cpack -G TXZ
  - cpack -G DEB
-
  matrix:
    only:
      - image: Visual Studio 2017

  build_script:
    - mkdir build
    - cd build
    - if %PLATFORM%==x86 ( cmake -DBUILD_TESTING=ON .. )
    - if %PLATFORM%==x64 ( cmake -DBUILD_TESTING=ON -G "Visual Studio 15 2017 Win64" .. )
    - cmake --build . --config Release
    - cmake --build . --config Debug
    - cmake --build . --config RelWithDebInfo
  
  test_script:
    - ctest -C Debug
    - ctest -C Release
    - ctest -C RelWithDebInfo

  after_test:
  - cpack -G ZIP -C Release
  - cpack -G NSIS -C Release
  - ren *.exe ??????????????????????????.??.??.??-Release.exe
  - ren *.zip ??????????????????????????.??.??.??-Release.zip
  - move libriffcpp-* Release
  - cpack -G ZIP -C Debug
  - cpack -G NSIS -C Debug
  - ren *.exe ??????????????????????????.??.??.??-Debug.exe
  - ren *.zip ??????????????????????????.??.??.??-Debug.zip
  - move libriffcpp-* Debug
  - cpack -G ZIP -C RelWithDebInfo
  - cpack -G NSIS -C RelWithDebInfo
  - ren *.exe ??????????????????????????.??.??.??-RelWithDebInfo.exe
  - ren *.zip ??????????????????????????.??.??.??-RelWithDebInfo.zip
  - move libriffcpp-* RelWithDebInfo


artifacts:
  - path: 'build/libriffcpp-*.tar.bz2'
  - path: 'build/libriffcpp-*.tar.xz'
  - path: 'build/libriffcpp-*.deb'
  - path: 'build/*/libriffcpp-*.exe'
  - path: 'build/*/libriffcpp-*.zip'

deploy:
  - provider: GitHub
    auth_token:
      secure: PKQ8wyiF5mNTAWbKepUrcnec7bucnXJ/T+Ip1NfxblviD6BqamxMuSQI1Kk5mCm+
    artifact: /.*/
    draft: true
    prerelease: false
    on:
      branch: master
      APPVEYOR_REPO_TAG: true