version: 1.0.0.{build}
image:
- Visual Studio 2017
- Ubuntu1804

platform:
  - x86
  - x64

for:
-
  matrix:
    only:
      - image: Ubuntu1804
      - platform: x64

  build_script:
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTING=ON ..
    - cmake --build . --config Release

  test_script:
    - ctest

  after_test:
  - cpack -G ZIP
-
  matrix:
    only:
      - image: Visual Studio 2017

  build_script:
    - mkdir build
    - cd build
    - if %PLATFORM%==x86 ( cmake -DBUILD_TESTING=ON .. )
    - if %PLATFORM%==x64 ( cmake -DBUILD_TESTING=ON -G "Visual Studio 15 2017 Win64" .. )
    - cmake --build . --config Release
    - cmake --build . --config Debug
    - cmake --build . --config RelWithDebInfo
  
  test_script:
    - ctest -C Debug
    - ctest -C Release
    - ctest -C RelWithDebInfo


artifacts:
  - path: 'build/*/libriffcpp-*.zip'

deploy:
  - provider: GitHub
    auth_token:
      secure: PKQ8wyiF5mNTAWbKepUrcnec7bucnXJ/T+Ip1NfxblviD6BqamxMuSQI1Kk5mCm+
    artifact: /.*/
    draft: true
    prerelease: false
    on:
      branch: master
      APPVEYOR_REPO_TAG: true