name: Build test
on: [push, pull-request]

jobs:
  build:
    name: Linux build
    runs-on: ubuntu-18.04
    steps:
    - run: mkdir build
    - run: cd build
    - run: cmake ${GITHUB_WORKSPACE} -DBUILD_SHARED_LIBS=${BUILD_SHARED} -DCMAKE_BUILD_TYPE=${BUILD_CONFIG} -DBUILD_TESTING=ON
    - run: cmake --build .
    - run: ctest