name: Build & test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        shared: ['ON', 'OFF']
        buildtype: ['Debug', 'Release']
    
    steps:
    - uses: actions/checkout@v1
    - run: mkdir build
    - run: cd build
    - run: cmake ${GITHUB_WORKSPACE} -DBUILD_SHARED_LIBS=${{ matrix.shared }} -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} -DBUILD_TESTING=ON
    - run: cmake --build .
    - run: ctest
